language: python

python:
  - "2.7"

install:
 - sudo apt-get install python-serial python-qwt5-qt4
 - sudo apt-get install python-qt4
 - sudo apt-get install build-essential

script:
 - python ./src/ServoTool.py
